### ISSUE TITLE
VB6 NoCase Patch seems for a different DLL Version

### ISSUE THREAD

**Issue by Tragen** [dzzie/addins#2]
My VBA6.DLL ist 6.0.0.9782 and if I try to apply your patch I get the message that some bytes don't match.

**Comment by Tragen** [comment]
My VBA6.DLL ist 6.0.0.9782 and if I try to apply your patch I get the message that some bytes don't match.

**Comment by dzzie** [comment]
yeah I am going to remove that patch. It was from another author i mirrored here, 
I found the offsets they were targeting in my build and its a bad patch. they must not use option explicit but it reveals that Dim a <> Dim A  so I dont think it will ever work. I spent a day on trying to find an alt place to patch and while I could correct the IDE editor, the compile phase always failed if using option explicit because the var was not dimmed.
